// Random three-word slug generator for new Record filenames
// (specs/record-format.md § Filename). The exact wordlist is an
// implementation detail; the contract is just "human-readable, low
// collision risk."
//
// Pattern: adjective-plural-noun-verb (e.g. "quiet-cats-sneeze"). 96 × 96 × 96
// ≈ 884k combinations, plenty for a release cycle's worth of Records.
// `dv add` checks for filename collisions and retries up to a few times
// before giving up.

const ADJECTIVES = [
  "ancient",
  "bashful",
  "blue",
  "bold",
  "brave",
  "bright",
  "calm",
  "clever",
  "cosmic",
  "cozy",
  "crisp",
  "curious",
  "daring",
  "dewy",
  "early",
  "eager",
  "earnest",
  "easy",
  "eerie",
  "fancy",
  "feral",
  "fierce",
  "fleet",
  "fluffy",
  "fond",
  "free",
  "fresh",
  "gentle",
  "giddy",
  "glad",
  "golden",
  "grumpy",
  "happy",
  "honest",
  "hungry",
  "icy",
  "jaunty",
  "jolly",
  "keen",
  "kind",
  "lazy",
  "lively",
  "loud",
  "lucky",
  "lush",
  "mighty",
  "mild",
  "modest",
  "noisy",
  "olive",
  "patient",
  "petty",
  "plump",
  "polite",
  "proud",
  "quick",
  "quiet",
  "rapid",
  "rosy",
  "rough",
  "rowdy",
  "rusty",
  "salty",
  "shiny",
  "shy",
  "silent",
  "silly",
  "silver",
  "sleepy",
  "small",
  "smart",
  "smooth",
  "snug",
  "soft",
  "solid",
  "sour",
  "spry",
  "stark",
  "steady",
  "stern",
  "still",
  "stoic",
  "stout",
  "subtle",
  "sunny",
  "swift",
  "tame",
  "tense",
  "tidy",
  "timid",
  "tiny",
  "tough",
  "vivid",
  "wary",
  "weary",
  "wild",
];

const PLURAL_NOUNS = [
  "ants",
  "apples",
  "badgers",
  "bagels",
  "bananas",
  "bears",
  "beavers",
  "bees",
  "bells",
  "birds",
  "boots",
  "books",
  "bottles",
  "boxes",
  "brooms",
  "bubbles",
  "buffalo",
  "bushes",
  "cabbages",
  "candles",
  "cats",
  "cherries",
  "chickens",
  "clouds",
  "comets",
  "coyotes",
  "crabs",
  "cranes",
  "creatures",
  "crickets",
  "crows",
  "deer",
  "dogs",
  "ducks",
  "eagles",
  "elks",
  "ferns",
  "ferrets",
  "finches",
  "fish",
  "flies",
  "foxes",
  "frogs",
  "geese",
  "ghosts",
  "giraffes",
  "gnomes",
  "goats",
  "gourds",
  "hamsters",
  "hares",
  "hawks",
  "hens",
  "hippos",
  "horses",
  "kettles",
  "kites",
  "ladders",
  "lakes",
  "lamps",
  "leaves",
  "lemons",
  "lions",
  "magpies",
  "melons",
  "mice",
  "moles",
  "mountains",
  "mussels",
  "newts",
  "otters",
  "owls",
  "oxen",
  "pandas",
  "parrots",
  "pears",
  "penguins",
  "ponds",
  "puppies",
  "rabbits",
  "raccoons",
  "ravens",
  "rivers",
  "robins",
  "scorpions",
  "seals",
  "skunks",
  "snails",
  "snakes",
  "sparrows",
  "spiders",
  "squirrels",
  "stones",
  "swans",
  "tigers",
  "toads",
  "wolves",
  "yaks",
];

const VERBS = [
  "amble",
  "argue",
  "balance",
  "bark",
  "bask",
  "bite",
  "blink",
  "blush",
  "bounce",
  "brew",
  "burrow",
  "buzz",
  "carry",
  "chant",
  "chase",
  "chatter",
  "cheer",
  "chew",
  "chirp",
  "climb",
  "creep",
  "croak",
  "crow",
  "dance",
  "dash",
  "delay",
  "doodle",
  "drift",
  "drink",
  "drop",
  "drowse",
  "echo",
  "eat",
  "explore",
  "fetch",
  "flap",
  "float",
  "flutter",
  "freeze",
  "frown",
  "frolic",
  "gallop",
  "gather",
  "giggle",
  "glide",
  "glow",
  "graze",
  "growl",
  "grumble",
  "hatch",
  "hide",
  "hoard",
  "hop",
  "howl",
  "hover",
  "hum",
  "hunt",
  "hurry",
  "jump",
  "juggle",
  "kick",
  "knock",
  "land",
  "leap",
  "linger",
  "march",
  "meow",
  "mumble",
  "munch",
  "nap",
  "nestle",
  "nibble",
  "nod",
  "paint",
  "patrol",
  "pause",
  "peck",
  "ponder",
  "pounce",
  "pout",
  "prance",
  "preen",
  "puff",
  "purr",
  "race",
  "rattle",
  "rest",
  "rise",
  "roar",
  "run",
  "rustle",
  "scamper",
  "scatter",
  "scoot",
  "scratch",
  "scream",
  "scuttle",
  "shimmer",
  "shiver",
  "shout",
  "shuffle",
  "sigh",
  "sing",
  "skip",
  "slide",
  "slither",
  "smile",
  "sneeze",
  "snore",
  "snuggle",
  "soar",
  "splash",
  "sprint",
  "squawk",
  "stamp",
  "stretch",
  "stroll",
  "strut",
  "stumble",
  "sway",
  "swim",
  "swing",
  "tango",
  "thump",
  "tickle",
  "tiptoe",
  "trot",
  "tumble",
  "turn",
  "twirl",
  "twist",
  "vanish",
  "wade",
  "wail",
  "wait",
  "wander",
  "warble",
  "watch",
  "weave",
  "whirl",
  "whisper",
  "whistle",
  "wiggle",
  "wobble",
  "yawn",
];

/**
 * Test seam: callers can inject a deterministic RNG to make slug generation
 * repeatable in tests. Default uses `Math.random`; the spec says nothing
 * about cryptographic randomness here.
 */
export interface SlugRandomSource {
  /** Returns a float in `[0, 1)`, like `Math.random`. */
  next(): number;
}

/** The default {@link SlugRandomSource}, backed by `Math.random`. */
export const defaultRandomSource: SlugRandomSource = {
  next: () => Math.random(),
};

interface GenerateSlugArgs {
  randomSource?: SlugRandomSource;
}

export function generateSlug(args: GenerateSlugArgs = {}): string {
  const randomSource = args.randomSource ?? defaultRandomSource;
  const adjective = pickRandomly({ wordlist: ADJECTIVES, randomSource });
  const pluralNoun = pickRandomly({ wordlist: PLURAL_NOUNS, randomSource });
  const verb = pickRandomly({ wordlist: VERBS, randomSource });
  return `${adjective}-${pluralNoun}-${verb}`;
}

interface PickRandomlyArgs {
  wordlist: readonly string[];
  randomSource: SlugRandomSource;
}

function pickRandomly(args: PickRandomlyArgs): string {
  const { wordlist, randomSource } = args;
  const index = Math.floor(randomSource.next() * wordlist.length);
  return wordlist[index] ?? wordlist[0]!;
}
