// Installs a `dv` shim that runs the in-tree source against the **live**
// deno.json — not a snapshot. The standard `deno install` would copy
// deno.json into ~/.deno/bin/.dv/ at install time; any change to the
// repo's deno.json (deps, imports, tasks) then leaves the shim stale
// until `deno install -f` is re-run. That's a real footgun while
// iterating on milestones, so this dogfood shim points at the live file
// instead.
//
// Cross-platform: the installer itself is Deno TS and runs on every
// host. The launcher it writes is platform-appropriate — a POSIX `sh`
// shebang script on macOS/Linux, a `.cmd` batch file on Windows. Both
// invoke the same `deno run --config <live deno.json> <main.ts>` under
// the hood; only the wrapper syntax differs.
//
// Run via `deno task install`. The matching uninstaller is
// `deno task uninstall` (this script with `--uninstall`).

import { resolve } from "@std/path";

const SHIM_NAME = "dv";

export type HostPlatform = "windows" | "unix";

function detectPlatform(): HostPlatform {
  return Deno.build.os === "windows" ? "windows" : "unix";
}

export function chooseShimFileName(platform: HostPlatform): string {
  return platform === "windows" ? `${SHIM_NAME}.cmd` : SHIM_NAME;
}

interface ResolvePathsResult {
  repoRoot: string;
  denoInstallBin: string;
  shimPath: string;
  legacySnapshotDir: string;
  platform: HostPlatform;
}

function resolvePaths(): ResolvePathsResult {
  const platform = detectPlatform();
  const scriptDir = new URL(".", import.meta.url).pathname;
  const repoRoot = resolve(scriptDir, "../../../..");
  const denoInstallRoot = resolveDenoInstallRoot(platform);
  const denoInstallBin = `${denoInstallRoot}/bin`;
  const shimFileName = platform === "windows" ? `${SHIM_NAME}.cmd` : SHIM_NAME;
  return {
    repoRoot,
    denoInstallBin,
    shimPath: `${denoInstallBin}/${shimFileName}`,
    legacySnapshotDir: `${denoInstallBin}/.${SHIM_NAME}`,
    platform,
  };
}

function resolveDenoInstallRoot(platform: HostPlatform): string {
  const fromEnv = Deno.env.get("DENO_INSTALL_ROOT");
  if (fromEnv) return fromEnv;
  const homeEnvVar = platform === "windows" ? "USERPROFILE" : "HOME";
  const homeDir = Deno.env.get(homeEnvVar) ?? "~";
  return `${homeDir}/.deno`;
}

export interface RenderLauncherArgs {
  repoRoot: string;
  platform: HostPlatform;
}

export function renderLauncher(args: RenderLauncherArgs): string {
  const pathSeparator = args.platform === "windows" ? "\\" : "/";
  const joinPath = (...segments: string[]): string =>
    segments.join(pathSeparator);
  const configPath = joinPath(args.repoRoot, "deno.json");
  const entryPath = joinPath(args.repoRoot, "apps", "cli", "src", "main.ts");
  return args.platform === "windows"
    ? renderWindowsLauncher({ configPath, entryPath })
    : renderUnixLauncher({ configPath, entryPath });
}

interface PlatformLauncherArgs {
  configPath: string;
  entryPath: string;
}

function renderUnixLauncher(args: PlatformLauncherArgs): string {
  return `#!/bin/sh
# dv — dev shim. Runs the in-tree source against the LIVE deno.json so
# dependency / import / task changes don't require re-installing.
# Generated by \`deno task install\` (apps/cli/src/scripts/install-dev-shim.ts).
exec deno run \\
  --allow-all \\
  --config "${args.configPath}" \\
  "${args.entryPath}" \\
  "$@"
`;
}

function renderWindowsLauncher(args: PlatformLauncherArgs): string {
  // Windows paths in deno.json/entryPath may contain backslashes already
  // (set by Deno.build.os === 'windows' code paths); they go in quoted
  // strings, so we don't need extra escaping.
  return `@echo off
REM dv — dev shim. Runs the in-tree source against the LIVE deno.json so
REM dependency / import / task changes don't require re-installing.
REM Generated by \`deno task install\` (apps/cli/src/scripts/install-dev-shim.ts).
deno run --allow-all --config "${args.configPath}" "${args.entryPath}" %*
`;
}

interface InstallShimArgs {
  shimPath: string;
  platform: HostPlatform;
  launcherContents: string;
}

async function installShim(args: InstallShimArgs): Promise<void> {
  await Deno.writeTextFile(args.shimPath, args.launcherContents);
  // chmod is a no-op on Windows but harmless; we skip it to avoid the
  // platform-specific permission set the runtime would otherwise apply.
  if (args.platform !== "windows") {
    await Deno.chmod(args.shimPath, 0o755);
  }
}

async function cleanupLegacySnapshot(snapshotDir: string): Promise<void> {
  try {
    await Deno.remove(snapshotDir, { recursive: true });
  } catch (caughtError) {
    if (!(caughtError instanceof Deno.errors.NotFound)) throw caughtError;
  }
}

async function removeShim(shimPath: string): Promise<boolean> {
  try {
    await Deno.remove(shimPath);
    return true;
  } catch (caughtError) {
    if (caughtError instanceof Deno.errors.NotFound) return false;
    throw caughtError;
  }
}

async function runInstall(): Promise<number> {
  const paths = resolvePaths();
  await Deno.mkdir(paths.denoInstallBin, { recursive: true });
  const launcherContents = renderLauncher({
    repoRoot: paths.repoRoot,
    platform: paths.platform,
  });
  await installShim({
    shimPath: paths.shimPath,
    platform: paths.platform,
    launcherContents,
  });
  await cleanupLegacySnapshot(paths.legacySnapshotDir);
  console.log(`installed ${SHIM_NAME} → ${paths.shimPath}`);
  console.log(`launches in-tree source from ${paths.repoRoot}`);
  console.log(
    `(live deno.json — no re-install needed when imports or deps change)`,
  );
  return 0;
}

async function runUninstall(): Promise<number> {
  const paths = resolvePaths();
  const removedShim = await removeShim(paths.shimPath);
  await cleanupLegacySnapshot(paths.legacySnapshotDir);
  console.log(
    removedShim
      ? `removed ${paths.shimPath}`
      : `${paths.shimPath} was not installed`,
  );
  return 0;
}

function main(argv: string[]): Promise<number> {
  if (argv.includes("--uninstall")) return runUninstall();
  return runInstall();
}

if (import.meta.main) {
  Deno.exit(await main(Deno.args));
}
