// Installs a `dv` shim that runs the in-tree source against the **live**
// deno.json — not a snapshot. The standard `deno install` would copy
// deno.json into ~/.deno/bin/.dv/ at install time; any change to the
// repo's deno.json (deps, imports, tasks) then leaves the shim stale
// until `deno install -f` is re-run. That's a real footgun while
// iterating on milestones, so this dogfood shim points at the live file
// instead.
//
// Trade-offs:
//   - Only POSIX sh today. Windows would need a `.cmd` variant.
//   - The shim hard-codes the repo's absolute path. Moving the repo
//     requires re-running this installer.
//
// Run via `deno task install`. The matching uninstaller is
// `deno task uninstall` (this script with `--uninstall`).

import { resolve } from "@std/path";

const SHIM_NAME = "dv";

interface ResolvePathsResult {
  repoRoot: string;
  denoInstallBin: string;
  shimPath: string;
  legacySnapshotDir: string;
}

function resolvePaths(): ResolvePathsResult {
  const scriptDir = new URL(".", import.meta.url).pathname;
  const repoRoot = resolve(scriptDir, "../../../..");
  const denoInstallRoot =
    Deno.env.get("DENO_INSTALL_ROOT") ?? `${Deno.env.get("HOME") ?? "~"}/.deno`;
  const denoInstallBin = `${denoInstallRoot}/bin`;
  return {
    repoRoot,
    denoInstallBin,
    shimPath: `${denoInstallBin}/${SHIM_NAME}`,
    legacySnapshotDir: `${denoInstallBin}/.${SHIM_NAME}`,
  };
}

interface InstallShimArgs {
  repoRoot: string;
  shimPath: string;
}

async function installShim(args: InstallShimArgs): Promise<void> {
  const launcherScript = `#!/bin/sh
# dv — dev shim. Runs the in-tree source against the LIVE deno.json so
# dependency / import / task changes don't require re-installing.
# Generated by \`deno task install\` (see apps/cli/src/scripts/
# install-dev-shim.ts).
exec deno run \\
  --allow-all \\
  --config "${args.repoRoot}/deno.json" \\
  "${args.repoRoot}/apps/cli/src/main.ts" \\
  "$@"
`;
  await Deno.writeTextFile(args.shimPath, launcherScript);
  await Deno.chmod(args.shimPath, 0o755);
}

async function cleanupLegacySnapshot(snapshotDir: string): Promise<void> {
  try {
    await Deno.remove(snapshotDir, { recursive: true });
  } catch (caughtError) {
    if (!(caughtError instanceof Deno.errors.NotFound)) throw caughtError;
  }
}

async function removeShim(shimPath: string): Promise<boolean> {
  try {
    await Deno.remove(shimPath);
    return true;
  } catch (caughtError) {
    if (caughtError instanceof Deno.errors.NotFound) return false;
    throw caughtError;
  }
}

async function runInstall(): Promise<number> {
  const { repoRoot, denoInstallBin, shimPath, legacySnapshotDir } =
    resolvePaths();
  await Deno.mkdir(denoInstallBin, { recursive: true });
  await installShim({ repoRoot, shimPath });
  await cleanupLegacySnapshot(legacySnapshotDir);
  console.log(`installed ${SHIM_NAME} → ${shimPath}`);
  console.log(`launches in-tree source from ${repoRoot}`);
  console.log(
    `(live deno.json — no re-install needed when imports or deps change)`,
  );
  return 0;
}

async function runUninstall(): Promise<number> {
  const { shimPath, legacySnapshotDir } = resolvePaths();
  const removedShim = await removeShim(shimPath);
  await cleanupLegacySnapshot(legacySnapshotDir);
  console.log(
    removedShim ? `removed ${shimPath}` : `${shimPath} was not installed`,
  );
  return 0;
}

function main(argv: string[]): Promise<number> {
  if (argv.includes("--uninstall")) return runUninstall();
  return runInstall();
}

if (import.meta.main) {
  Deno.exit(await main(Deno.args));
}
